gif_values_poly:
	convert -delay 50 -loop 0 ./images/plot_values/polynom/*.png poly_values.gif

gif_values_gradBoost:
	convert -delay 50 -loop 0 ./images/plot_values/gradBoost/*.png gradBoost_values.gif

gif_values_gaussian:
	convert -delay 50 -loop 0 ./images/plot_values/gaussian/*.png gaussian_values.gif